# Autogenerated file
def render(times, validationMessage, validationStyle, minTimeDiff, minTicks, maxTicks, ticksSettings):
    yield """<html>  
    <head>
        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">
        <title>Fish feeder</title>
        <link rel=\"stylesheet\" href=\"static/feeder.css\">
        <script type=\"application/javascript\">
            const times = """
    yield str(times)
    yield """;
            const validationMessage = """
    yield str(validationMessage)
    yield """;
            const MIN_TIME_DIFF = """
    yield str(minTimeDiff)
    yield """;
            const MIN_TICKS = """
    yield str(minTicks)
    yield """
            const MAX_TICKS = """
    yield str(maxTicks)
    yield """
        </script> 
        <!-- SVG icons from https://www.svgrepo.com/collection/nilicons-rounded-interface-icons/ -->
    </head>
    <body>
        <form action=\"\" method=\"POST\">
            <span>Feed</span>
            <input type=\"number\" min=\""""
    yield str(minTicks)
    yield """\" max=\""""
    yield str(maxTicks)
    yield """\" name=\"ticks\" required value=\""""
    yield str(ticksSettings)
    yield """\"/>
            <span>ticks</span>
            <input type=\"submit\" class=\"app-button\" name=\"feed_action\" value=\"Feed\"/>
        </form>

        <hr>
        <p id=\"validationError\" class=\"hideInMoment """
    yield str(validationStyle)
    yield """\"><script>document.write(validationMessage);</script>&nbsp;</p>
        <form action=\"\" method=\"POST\" onsubmit=\"return validateTimes()\">
            <table id=\"table\" class=\"styled-table\">
                <thead>
                    <tr>
                        <th style=\"min-width:120px\">Time</th>
                        <th style=\"min-width:80px\">Ticks</th>
                        <th style=\"min-width:30px\">&nbsp;</th>
                    </tr>
                </thead>
                <tbody id=\"tblTbody\">
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan=\"3\">
                            <span>
                                <input id=\"submit\" class=\"app-button\" type=\"submit\" name=\"settings_submit\" value=\"Submit\"/>
                            </span>
                            <span>
                                <button class=\"app-button\" onclick=\"insertRow()\"><img height=\"15px\" src=\"static/add-svgrepo-com.svg\" alt=\"Add Row\"></button>      
                            </span>
                            <span>
                                <!--<input id=\"cancel\" class=\"app-button\" type=\"submit\" name=\"settings_cancel\" value=\"Cancel\"/>-->      
                                <input id=\"cancel\" class=\"app-button\" type=\"button\" name=\"settings_cancel\" value=\"Cancel\">   
                            </span>
                        </td>
                    </tr>
                </tfoot>                
            </table>
        </form>       
    </body>
    <script src=\"static/feeder.js\"></script>
</html>
"""
